clc;
clear;
close all;
x = [1 2 3 4]; 
X = fft(x); 
x_reconstructed = ifft(X);
subplot(3,1,1);
stem(x, 'filled');
title('Original Signal x[n]');
xlabel('n');
ylabel('Amplitude');
subplot(3,1,2);
stem(abs(X), 'filled');
title('Magnitude of DFT X[k]');
xlabel('k');
ylabel('|X[k]|');
subplot(3,1,3);
stem(real(x_reconstructed), 'filled');
title('Reconstructed Signal x[n] (IDFT)');
xlabel('n');
ylabel('Amplitude');
disp('DFT of the signal x[n]:');
disp(X);
disp('Reconstructed signal using IDFT:');
disp(x_reconstructed);